# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: pwsh
        run: |
          cd .\build\
          & .\Generate-Windows-Provisioning-Script.ps1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ProvisionWindows.ps1
          path: ProvisionWindows.ps1
      
      # Attach the file to the release if it is a release event
      - name: Release Artifacts
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ProvisionWindows.ps1
          asset_name: ProvisionWindows.ps1
          asset_content_type: text/plain
